In [119]:
import pandas as pd
import numpy as np

Importing datasets

In [120]:
movies_df = pd.read_csv("movies.csv")
credits_df = pd.read_csv("credits.csv")

Data Exploration

In [121]:
movies_df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",04-09-1992,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],26-12-2011,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",13-10-2013,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",03-05-2012,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",05-08-2005,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [122]:
credits_df

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [123]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [124]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Merging movie dataset and credit dataset

In [125]:
movies_df = movies_df.merge(credits_df, on = "title")

In [126]:
movies_df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [127]:
movies_df.shape

(4808, 23)

In [128]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [129]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4808 entries, 0 to 4807
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4808 non-null   int64
 1   genres                4808 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4808 non-null   int64
 4   keywords              4808 non-null   object
 5   original_language     4808 non-null   object
 6   original_title        4808 non-null   object
 7   overview              4805 non-null   object
 8   popularity            4808 non-null   float64
 9   production_companies  4808 non-null   object
 10  production_countries  4808 non-null   object
 11  release_date          4807 non-null   object
 12  revenue               4808 non-null   int64
 13  runtime               4806 non-null   float64
 14  spoken_languages      4808 non-null   object
 15  status                4808 non-null   object
 16  tagline               3964 non-null   object
 17  title                 4808 non-null   object
 18  vote_average          4808 non-null   float64
 19  vote_count            4808 non-null   int64
 20  movie_id              4808 non-null   int64
 21  cast                  4808 non-null   object
 22  crew                  4808 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.5+ KB

Taking the useful columns

In [130]:
movies_df = movies_df[['id','title','overview','genres','keywords','cast','crew']]

In [131]:
movies_df

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [132]:
movies_df.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

Removing null values

In [133]:
movies_df.dropna(inplace=True)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\191851754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df.dropna(inplace=True)

In [134]:
movies_df.shape

(4805, 7)

In [135]:
movies_df.duplicated().sum()

0

In [136]:
movies_df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

Importing ast module, used for processing python abstract syntax grammar

In [137]:
import ast

In [138]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [139]:
movies_df['genres'] = movies_df['genres'].apply(convert)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\3796871074.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = movies_df['genres'].apply(convert)

In [140]:
movies_df['keywords'] = movies_df['keywords'].apply(convert)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\1082450020.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(convert)

In [141]:
movies_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [142]:
movies_df['cast'] = movies_df['cast'].apply(convert)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\166057444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['cast'] = movies_df['cast'].apply(convert)

In [143]:
movies_df

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

Fetching the director for each film

In [144]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [145]:
movies_df['crew_director'] = movies_df['crew'].apply(fetch_director)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2906947025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['crew_director'] = movies_df['crew'].apply(fetch_director)

In [146]:
movies_df

,id,title,overview,genres,keywords,cast,crew,crew_director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",[Robert Rodriguez]
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",[Edward Burns]
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",[Scott Smith]
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",[Daniel Hsia]
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [147]:
movies_df.drop(axis=1,columns='crew',inplace=True)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\946755848.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df.drop(axis=1,columns='crew',inplace=True)

In [148]:
movies_df

,id,title,overview,genres,keywords,cast,crew_director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...",[Edward Burns]
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...",[Scott Smith]
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...",[Daniel Hsia]
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [149]:
movies_df['overview'] = movies_df['overview'].apply(lambda x:x.split())

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\110895886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['overview'] = movies_df['overview'].apply(lambda x:x.split())

In [150]:
movies_df

,id,title,overview,genres,keywords,cast,crew_director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...",[Edward Burns]
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...",[Scott Smith]
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...",[Daniel Hsia]
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [151]:
movies_df.dropna(inplace=True)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\191851754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df.dropna(inplace=True)

In [152]:
movies_df['genres'] = movies_df['genres'].apply(lambda x:[i.replace(' ','') for i in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
movies_df['cast'] = movies_df['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies_df['crew_director'] = movies_df['crew_director'].apply(lambda x:[i.replace(' ','') for i in x])

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2464568803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['genres'] = movies_df['genres'].apply(lambda x:[i.replace(' ','') for i in x])
C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2464568803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2464568803.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['cast'] = movies_df['cast'].apply(lambda x:[i.replace(' ','') for i in x])
C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2464568803.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['crew_director'] = movies_df['crew_director'].apply(lambda x:[i.replace(' ','') for i in x])

In [153]:
movies_df

,id,title,overview,genres,keywords,cast,crew_director
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]
...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez]
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein, Cait...",[EdwardBurns]
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith]
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia]
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...","[BrianHerzlinger, JonGunn, BrettWinn]"

In [154]:
movies_df.isnull().sum()

id               0
title            0
overview         0
genres           0
keywords         0
cast             0
crew_director    0
dtype: int64

Combining overview, genres, keywords, cast, crew_director columns in tags column

In [155]:
movies_df['tags'] = movies_df['overview']+movies_df['genres']+movies_df['keywords']+movies_df['cast']+movies_df['crew_director']

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\704723958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['tags'] = movies_df['overview']+movies_df['genres']+movies_df['keywords']+movies_df['cast']+movies_df['crew_director']

In [156]:
movies_df

,id,title,overview,genres,keywords,cast,crew_director,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishÃ©, MarshaDietlein, Cait...",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...","[BrianHerzlinger, JonGunn, BrettWinn]","[Ever, since, the, second, grade, when, he, fi..."

In [157]:
new_movies_df = movies_df[['id','title','tags']]

In [159]:
new_movies_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [160]:
new_movies_df['tags'] = new_movies_df['tags'].apply(lambda x:" ".join(x) )

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\2086240923.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies_df['tags'] = new_movies_df['tags'].apply(lambda x:" ".join(x) )

In [161]:
new_movies_df

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [162]:
new_movies_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [163]:
new_movies_df['tags'] = new_movies_df['tags'].apply(lambda x:x.lower())

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\4198970324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies_df['tags'] = new_movies_df['tags'].apply(lambda x:x.lower())

In [164]:
new_movies_df

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4803,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4807,25975,My Date with Drew,ever since the second grade when he first saw ...

Vectorizing tags column (Converting text into vectors)

In [165]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [166]:
cv.fit_transform(new_movies_df['tags']).toarray().shape

(4805, 5000)

In [169]:
vectors = cv.fit_transform(new_movies_df['tags']).toarray()

In [170]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [173]:
len(cv.get_feature_names_out())

5000

In [174]:
import nltk

PorterStemmer removes the suffixes present in the english word

In [175]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [176]:
def stemming(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [177]:
new_movies_df['tags'] = new_movies_df['tags'].apply(stemming)

C:\Users\marti\AppData\Local\Temp\ipykernel_11208\1343896728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies_df['tags'] = new_movies_df['tags'].apply(stemming)

Cosine Similarity measures the similarity of two vectors.<br/>
It measures by checking the cosine of the angle between two vectors and determines if both the vectors are pointing at the same direction.

In [178]:
from sklearn.metrics.pairwise import cosine_similarity

In [180]:
similarity = cosine_similarity(vectors)

In [205]:
similarity

array([[1.        , 0.07142857, 0.05143445, ..., 0.02353104, 0.02571722,
        0.        ],
       [0.07142857, 1.        , 0.07715167, ..., 0.02353104, 0.        ,
        0.        ],
       [0.05143445, 0.07715167, 1.        , ..., 0.02541643, 0.        ,
        0.        ],
       ...,
       [0.02353104, 0.02353104, 0.02541643, ..., 1.        , 0.07624929,
        0.05083286],
       [0.02571722, 0.        , 0.        , ..., 0.07624929, 1.        ,
        0.05555556],
       [0.        , 0.        , 0.        , ..., 0.05083286, 0.05555556,
        1.        ]])

In [210]:
similarity

array([[1.        , 0.07142857, 0.05143445, ..., 0.02353104, 0.02571722,
        0.        ],
       [0.07142857, 1.        , 0.07715167, ..., 0.02353104, 0.        ,
        0.        ],
       [0.05143445, 0.07715167, 1.        , ..., 0.02541643, 0.        ,
        0.        ],
       ...,
       [0.02353104, 0.02353104, 0.02541643, ..., 1.        , 0.07624929,
        0.05083286],
       [0.02571722, 0.        , 0.        , ..., 0.07624929, 1.        ,
        0.05555556],
       [0.        , 0.        , 0.        , ..., 0.05083286, 0.05555556,
        1.        ]])

In [183]:
similarity[0].shape

(4805,)

This sorted list shows the relevancing of movie avatar compared to other movies

In [214]:
sorted(similarity[0], reverse=True)

[1.0000000000000002,
 0.23473823893078552,
 0.23294541397390256,
 0.2309782890611944,
 0.2252817784447915,
 0.21912524504463887,
 0.21398024625545647,
 0.21398024625545647,
 0.2123976976214366,
 0.21170244960998524,
 0.20935894733965596,
 0.20256711147285467,
 0.19839002137983244,
 0.19738550848793068,
 0.1930468356263361,
 0.19258222162991084,
 0.1904761904761905,
 0.1889822365046136,
 0.18824832213400472,
 0.1860968420796942,
 0.18609684207969418,
 0.1852396434087371,
 0.1852396434087371,
 0.1852396434087371,
 0.18523964340873708,
 0.18257418583505536,
 0.18184824186332701,
 0.18156825980064073,
 0.1800205749557739,
 0.17817416127494962,
 0.17699808135119716,
 0.17699808135119713,
 0.17636890537566463,
 0.17496355305594127,
 0.17295817388759027,
 0.17251638983558856,
 0.1711841970043652,
 0.17118419700436519,
 0.17078251276599332,
 0.1690308509457033,
 0.1683587574253685,
 0.1683587574253685,
 0.16718346377260584,
 0.16645007571529583,
 0.1648119469795901,
 0.16366341767699427,
 0.16366341767699427,
 0.16143660075018942,
 0.16116459280507608,
 0.16101529717988267,
 0.15936381457791915,
 0.15936381457791915,
 0.157485197087178,
 0.15649215928719035,
 0.15590239111558093,
 0.1559023911155809,
 0.1543033499620919,
 0.15275252316519466,
 0.1522038868295523,
 0.15194743527951726,
 0.15130688316720062,
 0.151247535495505,
 0.151247535495505,
 0.14969623771302396,
 0.14969623771302396,
 0.14847846772912465,
 0.14824986333222023,
 0.1469861839480328,
 0.14638501094227999,
 0.14458880781356395,
 0.1432670637653132,
 0.1432670637653132,
 0.1432670637653132,
 0.14285714285714288,
 0.14285714285714288,
 0.14085904245475275,
 0.14062009564580388,
 0.13977131156292244,
 0.13957263155977065,
 0.13957263155977065,
 0.13856849886842332,
 0.13856849886842332,
 0.13829563644637993,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.136504726557987,
 0.13638618139749523,
 0.13468700594029479,
 0.13397282541141675,
 0.13231403100624078,
 0.13231403100624078,
 0.13231403100624078,
 0.13231403100624078,
 0.13226001425322162,
 0.13226001425322162,
 0.13195808169029696,
 0.1315903389919538,
 0.1315903389919538,
 0.1315903389919538,
 0.13093073414159542,
 0.13093073414159542,
 0.130031582934249,
 0.12964074471043285,
 0.1286978904175574,
 0.12858612496840993,
 0.12858612496840993,
 0.12858612496840993,
 0.12858612496840993,
 0.1271711710197892,
 0.12598815766974242,
 0.12598815766974242,
 0.12598815766974242,
 0.12598815766974242,
 0.1259881576697424,
 0.12515654358043973,
 0.12515654358043973,
 0.12483755678647186,
 0.12389865694583801,
 0.12371791482634838,
 0.1235415527768502,
 0.1235415527768502,
 0.12344267996967354,
 0.12344267996967354,
 0.12309149097933272,
 0.12104550653376049,
 0.12104550653376049,
 0.12104550653376049,
 0.12104550653376049,
 0.12049067317796998,
 0.11952286093343936,
 0.11904761904761905,
 0.11904761904761905,
 0.11878277418329973,
 0.11853911695403994,
 0.11765520133375293,
 0.11765520133375293,
 0.11757927025044307,
 0.11664236870396086,
 0.11664236870396086,
 0.11664236870396086,
 0.11664236870396084,
 0.11631052629980887,
 0.11572751247156893,
 0.11572751247156893,
 0.11501092655705904,
 0.11501092655705904,
 0.11501092655705904,
 0.11501092655705904,
 0.11461365101225056,
 0.11461365101225056,
 0.11461365101225056,
 0.11396057645963795,
 0.11375393879832252,
 0.11375393879832252,
 0.1126872339638022,
 0.1126872339638022,
 0.11253728415158593,
 0.11253728415158593,
 0.11253728415158593,
 0.11135885079684352,
 0.11135885079684352,
 0.1113588507968435,
 0.11085479909473867,
 0.11065666703449763,
 0.11021667854435137,
 0.11021667854435135,
 0.11021667854435135,
 0.10910894511799621,
 0.1091089451179962,
 0.1091089451179962,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10744306187005072,
 0.10744306187005072,
 0.10699012312772824,
 0.10699012312772824,
 0.10699012312772824,
 0.1061988488107183,
 0.10619884881071828,
 0.10619884881071828,
 0.10619884881071828,
 0.10597597584982435,
 0.10585122480499262,
 0.10585122480499262,
 0.10585122480499262,
 0.10585122480499262,
 0.104990131391452,
 0.10482848367219183,
 0.10432810619146021,
 0.10432810619146021,
 0.10432810619146021,
 0.10432810619146021,
 0.10432810619146021,
 0.10403129732205989,
 0.10403129732205989,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10309826235529032,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10218988991416098,
 0.10218988991416098,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10130511230913847,
 0.10130511230913847,
 0.10101525445522108,
 0.10101525445522108,
 0.10101525445522108,
 0.10101525445522108,
 0.10101525445522108,
 0.10044292546128848,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.10012523486435178,
 0.09960238411119947,
 0.09960238411119947,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09883324222148016,
 0.09878259746169996,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09759000729485333,
 0.09720197391996738,
 0.09652341781316803,
 0.09652341781316803,
 0.09639253854237598,
 0.09639253854237598,
 0.09639253854237598,
 0.09639253854237598,
 0.09569487529386911,
 0.09523809523809525,
 0.09523809523809525,
 0.09523809523809525,
 0.09523809523809525,
 0.09523809523809525,
 0.09523809523809525,
 0.09523809523809523,
 0.09449111825230681,
 0.09449111825230681,
 0.09449111825230681,
 0.09449111825230681,
 0.09449111825230681,
 0.09449111825230681,
 0.09412416106700235,
 0.09412416106700235,
 0.09412416106700235,
 0.09412416106700235,
 0.09412416106700235,
 0.09412416106700235,
 0.09412416106700233,
 0.09304842103984709,
 0.09304842103984709,
 0.09304842103984709,
 0.09258200997725516,
 0.09258200997725516,
 0.09258200997725516,
 0.09221388919541469,
 0.09221388919541468,
 0.09212254307176114,
 0.09212254307176114,
 0.09200874124564723,
 0.09156219276643894,
 0.09100315103865801,
 0.09100315103865801,
 0.09100315103865801,
 0.09100315103865801,
 0.09100315103865801,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09078412990032037,
 0.09002982732126874,
 0.09002982732126874,
 0.09002982732126874,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.08908708063747481,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.08849904067559858,
 0.08817334283548109,
 0.08817334283548109,
 0.08817334283548109,
 0.08748177652797065,
 0.08748177652797065,
 0.08748177652797065,
 0.08748177652797065,
 0.08748177652797065,
 0.08748177652797065,
 0.08748177652797065,
 0.08728715609439695,
 0.08728715609439695,
 0.08728715609439695,
 0.08642716314028859,
 0.08642716314028857,
 0.08642716314028857,
 0.08642716314028857,
 0.08642716314028857,
 0.08642716314028857,
 0.08625819491779428,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08596023825918792,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08559209850218259,
 0.08478078067985947,
 0.08478078067985947,
 0.08478078067985947,
 0.08478078067985947,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.0839921051131616,
 0.0839921051131616,
 0.0839921051131616,
 0.0839921051131616,
 0.08322503785764791,
 0.08322503785764791,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.083141099321054,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08247860988423225,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08183170883849714,
 0.08175191193132877,
 0.08175191193132877,
 0.08175191193132877,
 0.08104408984731078,
 0.08104408984731078,
 0.08104408984731078,
 0.08104408984731078,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08058229640253804,
 0.08043618151097337,
 0.08035434036903079,
 0.08000256012288656,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07968190728895957,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07902607796935997,
 0.07902607796935997,
 0.07902607796935997,
 0.07902607796935997,
 0.07902607796935997,
 0.07902607796935997,
 0.07838618016696206,
 0.07838618016696206,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.07824607964359516,
 0.0777615791359739,
 0.0777615791359739,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07655590023509529,
 0.07655590023509529,
 0.07655590023509529,
 0.07655590023509529,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477615,
 0.07597371763975863,
 0.07540461810874112,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07509392614826384,
 0.07493633116627257,
 0.07484811885651198,
 0.07484811885651198,
 0.07484811885651198,
 0.07484811885651198,
 0.07484811885651198,
 0.07458533939516852,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07412493166611012,
 0.07377111135633176,
 0.07324975421315115,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.0727392967453308,
 0.0727392967453308,
 0.0727392967453308,
 0.0727392967453308,
 0.0727392967453308,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07229440390678199,
 0.07174960033341753,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07142857142857144,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07079923254047886,
 0.07059312080025176,
 0.07059312080025176,
 0.07059312080025176,
 0.07059312080025176,
 0.07059312080025176,
 0.06988565578146122,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06944193284588147,
 0.06944193284588147,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.0682523632789935,
 0.0682523632789935,
 0.0682523632789935,
 0.0682523632789935,
 0.06774797209007694,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06752237049095156,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06734350297014739,
 0.06694619270045785,
 0.0668153104781061,
 0.0668153104781061,
 0.0668153104781061,
 0.0668153104781061,
 0.0668153104781061,
 0.06664889599684098,
 0.06617222226472869,
 0.06613000712661082,
 0.06613000712661082,
 0.06613000712661082,
 0.06613000712661082,
 0.06613000712661082,
 0.06613000712661082,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06546536707079771,
 0.06506000486323554,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.0643489452087787,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06419407387663695,
 0.06366070140792303,
 0.0635855855098946,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06299407883487121,
 0.06241877839323594,
 0.06241877839323594,
 0.06241877839323594,
 0.06241877839323594,
 0.06241877839323594,
 0.06241877839323594,
 0.06241877839323594,
 0.06203228069323139,
 0.06203228069323139,
 0.061858957413174195,
 0.06185895741317419,
 0.06185895741317419,
 0.06185895741317419,
 0.06185895741317419,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06172133998483677,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.06131393394849658,
 0.060783067385483086,
 0.060783067385483086,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060522753266880246,
 0.060265755276773095,
 0.060265755276773095,
 0.060265755276773095,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.059391387091649865,
 0.05926955847701998,
 0.05926955847701998,
 0.05926955847701998,
 0.05926955847701998,
 0.05878963512522154,
 0.05878963512522154,
 0.05878963512522154,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198043,
 0.05832118435198042,
 0.05832118435198042,
 0.05832118435198042,
 0.05832118435198042,
 0.057863756235784464,
 0.05741692517632146,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05730682550612528,
 0.05698028822981897,
 0.05698028822981897,
 0.05698028822981897,
 0.05698028822981897,
 0.05698028822981897,
 0.05698028822981897,
 0.05655346358155584,
 0.0563436169819011,
 0.0563436169819011,
 0.0563436169819011,

In [215]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1920, 0.23473823893078552),
 (1216, 0.23294541397390256),
 (582, 0.2309782890611944),
 (539, 0.2252817784447915),
 (507, 0.21912524504463887)]

In [216]:
def recommend(movie):
    movie_index = new_movies_df[new_movies_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_movies_df.iloc[i[0]].title)

In [217]:
recommend('Avatar')

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [218]:
recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
The Avengers
Thor